CREATE TABLE CITIES
(
    CITY_ID INT PRIMARY KEY,
    CITY CHAR(20),
    STATE CHAR(20)
);

CREATE TABLE WAREHOUSES
(
    WAREHOUSE_ID INT PRIMARY KEY,
    WNAME CHAR(30),
    LOCATION CHAR(20),
    CITY_ID INT,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES (CITY_ID)
);

CREATE TABLE STORES
(
    STORE_ID INT PRIMARY KEY,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20),
    WAREHOUSE_ID INT,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID)
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT PRIMARY KEY,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CITY_ID INT,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES (CITY_ID)
);

CREATE TABLE ORDERS
(
    ORDER_ID INT PRIMARY KEY,
    ONO INTEGER,
    ODATE DATE,
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE ITEMS
(
    ITEM_ID INT PRIMARY KEY,
    ITEMNO INTEGER,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2)
);

CREATE TABLE ORDER_ITEMS
(
    ORDER_ID INT,
    ITEM_ID INT,
    ORDERED_QUANTITY INT,
    PRIMARY KEY (ORDER_ID, ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID)
);

CREATE TABLE STORE_ITEMS
(
    STORE_ID INT,
    ITEM_ID INT,
    QUANTITY INT,
    PRIMARY KEY (STORE_ID, ITEM_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID)
);
